"""
Coding Sub-Agent
Convergent / analytical bias preferred. Emits concrete artifacts.
"""

from .base import BaseAgent, AgentResult
from datetime import datetime
from typing import Dict
import logging
import textwrap

logger = logging.getLogger("ck.coding")


class CodingAgent(BaseAgent):
    name = "coding"
    role = "code generation & artifact production"

    async def run(self, task: Dict) -> AgentResult:
        started = datetime.utcnow()
        mood = await self.current_mood()
        goal = task.get("goal") or task.get("spec") or "implement requested feature"
        language = task.get("language", "python")

        if language == "python":
            code = textwrap.dedent(f'''\
                """
                Auto-generated by CycleKernel CodingAgent
                Goal: {goal}
                Mood at generation: {mood.get("mood")}
                """

                def main():
                    print("CycleKernel artifact executing")
                    print("Goal satisfied: {goal[:80]}")
                    return 0

                if __name__ == "__main__":
                    raise SystemExit(main())
                ''')
        else:
            code = f"// CycleKernel artifact\n// Goal: {goal}\nconsole.log('ok');\n"

        artifact = {
            "language": language,
            "filename": task.get("filename", "artifact.py"),
            "content": code,
            "run_command": f"python /artifacts/{task.get('filename', 'artifact.py')}",
            "cognitive_context": mood.get("mood"),
        }

        logger.info(f"Coding artifact ready: {artifact['filename']}")
        return self._wrap(True, artifact, mood, started)
